### PR TITLE
Update browser title

### PR DESCRIPTION
**Pull request by gracekishino**

### CODE REVIEW

**Comment by mdwiltfong** [comment]
Off I just realized this deployment workflow shouldn't run until PRs are merged....Need to fix that. Although that has nothing to do with this change. Let me update the workflow beforehand though.

**Comment by gracekishino** [comment]
Thought it was something like that!

**Comment by mdwiltfong** [comment]
@gracekishino ,

Would you be so kind as to rebase this branch push it again? 🙏🏼

**Comment by gracekishino** [comment]
@mdwiltfong updated the branch and tests passing now :)

**Pull request merged**
